version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.8.0  #镜像
    container_name: elk_elasticsearch  #定义容器名称
    restart: always  #开机启动，失败也会一直重启
    environment:
      # 开启内存锁定
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # 指定单节点启动
      - discovery.type=single-node
    ulimits:
      # 取消内存相关限制  用于开启内存锁定
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./conf/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./conf/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.8.0
    container_name: elk_kibana
    restart: always
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200 #设置访问elasticsearch的地址
    ports:
      - "5601:5601"
  logstash:
    image: logstash:7.8.0
    container_name: elk_logstash
    restart: always
    volumes:
      - ./conf/logstash/logstash-springboot.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - "4560:4560"
#  filebeat:
#    image: elastic/filebeat:7.9.2
#    hostname: filebeat
#    restart: always
#    depends_on:
#      - logstash
#    user: root
#    volumes:
#      - ./conf/data/filebeat:/usr/share/filebeat/data
#      - ./conf/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
#      - ./conf/log:/usr/share/filebeat/logs
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      - TZ=Asia/Shanghai
#    command: [ "--strict.perms=false" ]

#汉化kibana
#docker exec -it elk_kibana /bin/bash -c "echo "i18n.locale: zh-CN" >> /opt/kibana/config/kibana.yml"
#docker restart elk_kibana