version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elk-es
    restart: always
    environment:
      # 开启内存锁定
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TAKE_FILE_OWNERSHIP=true"
      # 指定单节点启动
      - discovery.type=single-node
    ulimits:
      # 取消内存相关限制  用于开启内存锁定
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./logs/data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./logs/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.8.0
    container_name: elk-kibana
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elk-es:9200
      I18N_LOCALE: zh-CN
    ports:
      - "5601:5601"
  logstash:
    image: logstash:7.8.0
    container_name: elk-logstash
    restart: always
    environment:
      XPACK_MONITORING_ENABLED: "false"
      pipeline.batch.size: 10
    volumes:
      - ./conf/logstash/logstash-springboot.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "4560:4560" #设置端口
#  filebeat:
#    image: elastic/filebeat:7.9.2
#    hostname: filebeat
#    restart: always
#    depends_on:
#      - logstash
#    user: root
#    volumes:
#      - ./conf/data/filebeat:/usr/share/filebeat/data
#      - ./conf/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
#      - ./conf/log:/usr/share/filebeat/logs
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      - TZ=Asia/Shanghai
#    command: [ "--strict.perms=false" ]