version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    restart: always
    hostname: mysql
